version: "3.4"

services:

  monopoly-db:
    image: postgres
    container_name: monopoly-db
    hostname: monopoly-db
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: monopoly
      POSTGRES_USER: monopoly
      POSTGRES_PASSWORD: 1234
    volumes:
      - ../monopoly-devops/vol-pgsql:/var/lib/postgresql/data

  monopoly-web:
    container_name: monopoly-web
    hostname: monopoly-web
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/code:cached
    depends_on: 
      - monopoly-db

volumes:
  vol-pgsql: