# Generated by Django 3.0.4 on 2020-05-27 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200518_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playinguser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing_users', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Sprzedający'),
        ),
    ]
