# Generated by Django 3.0.4 on 2020-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_playinguser_prison'),
    ]

    operations = [
        migrations.AddField(
            model_name='playinguser',
            name='dice',
            field=models.BooleanField(default=False, verbose_name='Rzut kostką'),
        ),
        migrations.AddField(
            model_name='playinguser',
            name='get_out_of_jail_card',
            field=models.IntegerField(default=0, verbose_name='Karta wyjdź z więzienia'),
        ),
    ]
