# Generated by Django 3.0.4 on 2020-06-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200607_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playinguser',
            name='prison',
            field=models.IntegerField(blank=True, null=True, verbose_name='Liczba kolejek w więzieniu'),
        ),
    ]
