version: "3.4"

services:

  monopoly-db:
    image: postgres:12
    container_name: monopoly-db
    hostname: monopoly-db
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: monopoly
      POSTGRES_USER: monopoly
      POSTGRES_PASSWORD: 1234
    volumes:
      - ../monopoly-devops/vol-pgsql:/var/lib/postgresql/data
    networks: 
      - back-net

  monopoly-back:
    container_name: monopoly-back
    hostname: monopoly-back
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - redis:redis
    volumes:
      - .:/code:cached
    depends_on: 
      - monopoly-db
    networks: 
      - front_monopoly-net
      - back-net

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - redisdata:/data
    networks:
      - back-net
networks: 
  front_monopoly-net:
    external: true
  back-net:

volumes:
  vol-pgsql:
  redisdata: