# Generated by Django 3.0.4 on 2020-05-05 16:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa akcji')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_zero_houses', models.IntegerField(verbose_name='Czynsz za zero posiadłości')),
                ('fee_one_house', models.IntegerField(verbose_name='Czynsz za jedną posiadłość')),
                ('fee_two_houses', models.IntegerField(verbose_name='Czynsz za dwie posiadłości')),
                ('fee_three_houses', models.IntegerField(verbose_name='Czynsz za trzy posiadłości')),
                ('fee_four_houses', models.IntegerField(verbose_name='Czynsz za cztery posiadłości')),
                ('fee_five_houses', models.IntegerField(verbose_name='Czynsz za pięć posiadłości')),
                ('fee_six_houses', models.IntegerField(verbose_name='Czynsz za sześć posiadłości')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa dzielnicy')),
                ('price_per_house', models.IntegerField(verbose_name='Cena za domek')),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa typu pola')),
                ('parameter', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Parametry typu pola')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_types', to='api.Action', verbose_name='Akcja')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Cena za pole')),
                ('estate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estate', to='api.Estate')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.FieldType', verbose_name='Typ pola')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.Zone', verbose_name='Dzielnica')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Opis karty')),
                ('parameter', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Parametry karty')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.Action', verbose_name='Akcja')),
            ],
        ),
    ]
