# Generated by Django 3.0.4 on 2020-05-09 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Akcje'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Karta'},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': 'Posiadłości'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Pole'},
        ),
        migrations.AlterModelOptions(
            name='fieldtype',
            options={'verbose_name': 'Typ pola'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Strefa'},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Cena za pole')),
                ('isBuyingOffer', models.BooleanField(verbose_name='Oferta kupna')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Kupujący')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.Field', verbose_name='Pole')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_seller', to=settings.AUTH_USER_MODEL, verbose_name='Sprzedający')),
            ],
            options={
                'verbose_name': 'Oferty',
            },
        ),
        migrations.CreateModel(
            name='PlayingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Kolejność')),
                ('isActive', models.BooleanField(default=False, verbose_name='Aktywyny ruch')),
                ('isPlaying', models.BooleanField(default=False, verbose_name='Grający')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Budżet')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing_users', to='api.Field', verbose_name='Pole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing_users', to=settings.AUTH_USER_MODEL, verbose_name='Sprzedający')),
            ],
            options={
                'verbose_name': 'Grający użytkownicy',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estateNumber', models.IntegerField(blank=True, null=True, verbose_name='Liczba domków')),
                ('isPledged', models.BooleanField(default=False, verbose_name='Zastawiona nieruchomość')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.Field', verbose_name='Pole')),
                ('playingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.PlayingUser', verbose_name='Uzytkownik')),
            ],
            options={
                'verbose_name': 'Posiadłości',
            },
        ),
    ]
